# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Yingke-TV' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'AFNetworking', '~> 3.2.1'
  pod 'SDWebImage', '~> 5.0.0-beta3'
  pod 'Masonry', '~> 1.1.0'
  pod 'YYKit', '~> 1.0.9'

  # Pods for Yingke-TV

end
